export const ActionTypes = {
    SET_FOOD : "SET_FOOD",
    SELECTED_FOOD:"SELECTED_FOOD",
    REMOVE_SELECTED_FOOD:"REMOVE_SELECTED_FOOD",
    CART_FOOD:"CART_FOOD",
    REMOVE_CART_FOOD:"REMOVE_CART_FOOD",
    DECREASE_CART_FOOD:"DECREASE_CART_FOOD",
    REMOVE_ALL_CART_FOOD:"REMOVE_ALL_CART_FOOD",
    ORDER_FOOD : "ORDER_FOOD",
    REMOVE_ORDER_FOOD : "REMOVE_ORDER_FOOD",
    DECREASE_ORDER_FOOD:"DECREASE_ORDER_FOOD",
    REMOVE_ALL_ORDERS:"REMOVE_ALL_ORDERS",
    ORDER_CONFORM:"ORDER_CONFORM",
    
}